#ifndef __UITilesetH__
#define __UITilesetH__

#define TILE_Window_Mid_Mid 0
#define TILE_Window_Top_Left 1
#define TILE_Window_Top_Right 2
#define TILE_Window_Bottom_Left 3
#define TILE_Window_Bottom_Right 4
#define TILE_Window_Top_Mid 5
#define TILE_Window_Bottom_Mid 6
#define TILE_Window_Mid_Left 7
#define TILE_Window_Mid_Right 8
#define TILE_Window_Div_Vertical_Bottom 9
#define TILE_Window_Div_Horizontal_Left 10
#define TILE_Window_Div_Horizontal_Right 11
#define TILE_Window_Div_Horizontal_Mid 12
#define TILE_Window_Div_Vertical_Mid 13
#define TILE_Window_Div_Four_Way 14
#define TILE_BlueArrow_Down 15
#define TILE_BlueArrow_Up 16
#define TILE_BlueArrow_Right 17
#define TILE_BlueArrow_Left 18
#define TILE_CheckMark 19
#define TILE_SliderHandle 20
#define TILE_New_Mail_Icon 21
#define TILE_RotationArrow 22
#define TILE_ScrollbarHandle_Top 23
#define TILE_ScrollbarHandle_Middle 24
#define TILE_ScrollbarHandle_Bottom 25
#define TILE_Scrollbar_Top 26
#define TILE_Scrollbar_Middle 27
#define TILE_Scrollbar_Bottom 28
#define TILE_Rect_23 29
#define TILE_Rect_24 30
#define TILE_Rect_25 31
#define TILE_Rect_26 32
#define TILE_Rect_27 33
#define TILE_Rect_28 34
#define TILE_AsciiBar_A 35
#define TILE_AsciiBar_B 36
#define TILE_AsciiBar_C 37
#define TILE_AsciiBar_D 38
#define TILE_AsciiBar_E 39
#define TILE_AsciiBar_F 40
#define TILE_AsciiBar_G 41
#define TILE_AsciiBar_H 42
#define TILE_AsciiBar_I 43
#define TILE_AsciiBar_J 44
#define TILE_AsciiBar_K 45
#define TILE_AsciiBar_L 46
#define TILE_AsciiBar_M 47
#define TILE_AsciiBar_N 48
#define TILE_AsciiBar_O 49
#define TILE_AsciiBar_P 50
#define TILE_AsciiBar_Q 51
#define TILE_AsciiBar_R 52
#define TILE_AsciiBar_S 53
#define TILE_AsciiBar_T 54
#define TILE_AsciiBar_U 55
#define TILE_AsciiBar_V 56
#define TILE_AsciiBar_W 57
#define TILE_AsciiBar_X 58
#define TILE_AsciiBar_Y 59
#define TILE_AsciiBar_Z 60
#define TILE_AsciiBar_Left 61
#define TILE_AsciiBar_Right 62
#define TILE_AsciiBar_0 63
#define TILE_AsciiBar_1 64
#define TILE_AsciiBar_2 65
#define TILE_AsciiBar_3 66
#define TILE_AsciiBar_4 67
#define TILE_AsciiBar_5 68
#define TILE_AsciiBar_6 69
#define TILE_AsciiBar_7 70
#define TILE_AsciiBar_8 71
#define TILE_AsciiBar_9 72
#define TILE_AsciiBar_Space 73
#define TILE_Selection_Feather 74
#define TILE_Button_Circle 75
#define TILE_Button_Triangle 76
#define TILE_Button_Square 77
#define TILE_Button_Cross 78
#define TILE_Button_DPad_Left 79
#define TILE_Button_DPad_Up 80
#define TILE_Button_DPad_Right 81
#define TILE_Button_DPad_Down 82
#define TILE_Button_Left_Analog 83
#define TILE_Button_Right_Analog 84
#define TILE_Button_Start 85
#define TILE_Button_Select 86
#define TILE_Button_L1 87
#define TILE_Button_L2 88
#define TILE_Button_R1 89
#define TILE_Button_R2 90
#define TILE_Rect_85 91
#define TILE_AlternateWindowTop_Left 92
#define TILE_AlternateWindowTop_Mid 93
#define TILE_AlternateWindowTop_Right 94
#define TILE_Rect_89 95
#define TILE_AlternateWindowMid_Left 96
#define TILE_AlternateWindowMid_Mid 97
#define TILE_AlternateWindowMid_Right 98
#define TILE_AlternateWindowMid_Left_Expander 99
#define TILE_AlternateWindowMid_Mid_Expander 100
#define TILE_AlternateWindowMid_Right_Expander 101
#define TILE_Rect_93 102
#define TILE_Rect_94 103
#define TILE_LargeTitleBar_Left 104
#define TILE_LargeTitleBar_Mid 105
#define TILE_LargeTitleBar_Right 106
#define TILE_LargeTitleBar_Shade_Left 107
#define TILE_LargeTitleBar_Shade_Mid 108
#define TILE_LargeTitleBar_Shade_Right 109
#define TILE_Square_Selection_Rect_Top_Left 110
#define TILE_Square_Selection_Rect_Bottom_Left 111
#define TILE_Square_Selection_Rect_Mid_Left 112
#define TILE_Square_Selection_Rect_Top_Mid 113
#define TILE_Square_Selection_Rect_Mid_Mid 114
#define TILE_Square_Selection_Rect_Bottom_Mid 115
#define TILE_Square_Selection_Rect_Top_Right 116
#define TILE_Square_Selection_Rect_Mid_Right 117
#define TILE_Square_Selection_Rect_Bottom_Right 118
#define TILE_WhiteTriangle_Right 119
#define TILE_HPBar 120
#define TILE_SPBar 121
#define TILE_HPSP_TextArea_Left 122
#define TILE_HPSP_TextArea_Right 123
#define TILE_HPSPBar_Bar 124
#define TILE_Triangle_SW 125
#define TILE_WhiteTriangle_NW 126
#define TILE_WhiteTriangle_NE 127
#define TILE_WhiteTriangle_SE 128
#define TILE_WhiteLineRect_Top_Left 129
#define TILE_WhiteLineRect_Top_Mid 130
#define TILE_WhiteLineRect_Top_Right 131
#define TILE_WhiteLineRect_Mid_Left 132
#define TILE_WhiteLineRect_Mid_Mid 133
#define TILE_WhiteLineRect_Mid_Right 134
#define TILE_WhiteLineRect_Bottom_Left 135
#define TILE_WhiteLineRect_Bottom_Mid 136
#define TILE_WhiteLineRect_Bottom_Right 137
#define TILE_Text_ATTACK 138
#define TILE_WhiteSquare 139
#define TILE_Text_BATTLE_MODE 140
#define TILE_Text_On 141
#define TILE_Text_Off 142
#define TILE_GateMenu_Crystal 143
#define TILE_GateMenu_Crystal_Glow 144
#define TILE_PlayerHud_Left_Top 145
#define TILE_PlayerHud_Left_Bottom 146
#define TILE_RoundedSelectionRect_Top_Left 147
#define TILE_RoundedSelectionRect_Top_Right 148
#define TILE_RoundedSelectionRect_Mid_Left 149
#define TILE_RoundedSelectionRect_Mid_Right 150
#define TILE_RoundedSelectionRect_Top_Mid 151
#define TILE_RoundedSelectionRect_Bottom_Mid 152
#define TILE_RoundedSelectionRect_Bottom_Left 153
#define TILE_RoundedSelectionRect_Bottom_Right 154
#define TILE_Text_SELECT 155
#define TILE_Text_START 156
#define TILE_Tab_Left 157
#define TILE_Tab_Left_Overlapped 158
#define TILE_Tab_Mid 159
#define TILE_Tab_Right_Overlapped 160
#define TILE_Tab_Right 161
#define TILE_Tab_Window_Overlay_Left 162
#define TILE_Tab_Window_Overlay_Mid 163
#define TILE_Tab_Window_Overlay_Right 164
#define TILE_SliderBG_Left 165
#define TILE_SliderBG_Right 166
#define TILE_SliderBG_Mid 167
#define TILE_Icon_TwinBlade 168
#define TILE_Icon_Blade 169
#define TILE_Icon_HeavyBlade 170
#define TILE_Icon_Axe 171
#define TILE_Icon_Spear 172
#define TILE_Icon_Staff 173
#define TILE_Icon_Helmet 174
#define TILE_Icon_Armor 175
#define TILE_Icon_HandArmor 176
#define TILE_Icon_LegArmor 177
#define TILE_Icon_Item 178
#define TILE_Icon_Scroll 179
#define TILE_Icon_Exclaim 180
#define TILE_LAST_TILE 181

extern short UITileset[];
#endif
